[package]
name = "download-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
error-chain = "0.12.4"
reqwest = "0.11.11"
tokio = { version = "1.19.2", features = ["full"] }
