Vagrant.configure("2") do |config|

    config.vm.define "consul" do |c|
        c.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
        c.vm.box = "debian/bullseye64"
        c.vm.network "private_network", ip: "192.168.56.8"
        c.vm.provision "ansible" do |ansible|
            ansible.playbook = "image/playbook.yml"
            ansible.extra_vars = {
                consul: {
                    bind_addr: "0.0.0.0",
                    advertise_addr: "192.168.56.8"
                }
            }
        end
    end

end
