---

- name: Provision a Screem api server to be saved as an AMI
  hosts: all
  remote_user: eighty4-admin
  become: true
  tasks:

    - name: Install Screem api service
      import_role:
        name: compose
      vars:
        service_name: screem
        service_ports: ['8080']
        auth_with_ecr: true
