---

- name: Provision a TeamCity agent server to be saved as an AMI
  hosts: all
  remote_user: eighty4-admin
  become: true
  tasks:

    - name: Install TeamCity agent service
      import_role:
        name: compose
      vars:
        service_name: teamcity-agent
