Vagrant.configure("2") do |config|

    config.vm.define "consul" do |c|
        c.vm.hostname = "consul-server"
        c.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
        c.vm.box = "debian/bullseye64"
        c.vm.network "private_network", ip: "192.168.56.8"
        c.vm.provision "ansible" do |ansible|
            ansible.playbook = "image/consul.playbook.yml"
            ansible.extra_vars = {
                consul: {
                    node_name: "consul-node",
                    server: true,
                    bind_addr: "0.0.0.0",
                    advertise_addr: "192.168.56.8",
                    client_addr: "0.0.0.0",
                    bootstrap_expect: 1
                }
            }
        end
    end

    config.vm.define "app-js" do |aj|
        aj.vm.hostname = "app-js"
        aj.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
        aj.vm.box = "debian/bullseye64"
        aj.vm.network "private_network", ip: "192.168.56.9"
        aj.vm.synced_folder "app/js", "/app"
        aj.vm.provision "ansible" do |ansible|
            ansible.playbook = "image/consul.playbook.yml"
            ansible.extra_vars = {
                consul: {
                    configure_dns_forwarding: true,
                    node_name: "app-js-node",
                    server: false,
                    advertise_addr: "192.168.56.9",
                    bind_addr: "0.0.0.0",
                    retry_join: ["192.168.56.8"]
                }
            }
        end
        aj.vm.provision "shell" do |shell|
            shell.path = "app/install-node.sh"
        end
    end

    config.vm.define "app-rust" do |ar|
        ar.vm.hostname = "app-rust"
        ar.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
        ar.vm.box = "debian/bullseye64"
        ar.vm.network "private_network", ip: "192.168.56.10"
        ar.vm.synced_folder "app/rust", "/app"

        ar.vm.provision "shell" do |shell|
            shell.path = "app/install-rust.sh"
        end
    end

end
